/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      typography: () => ({
        jet: {
          css: {
            "--tw-prose-body": "var(--color-jet-700)",
            "--tw-prose-headings": "var(--color-jet-900)",
            "--tw-prose-lead": "var(--color-jet-600)",
            "--tw-prose-links": "var(--color-jet-900)",
            "--tw-prose-bold": "var(--color-jet-900)",
            "--tw-prose-counters": "var(--color-jet-500)",
            "--tw-prose-bullets": "var(--color-jet-300)",
            "--tw-prose-hr": "var(--color-jet-200)",
            "--tw-prose-quotes": "var(--color-jet-900)",
            "--tw-prose-quote-borders": "var(--color-jet-200)",
            "--tw-prose-captions": "var(--color-jet-500)",
            "--tw-prose-kbd": "var(--color-jet-900)",
            "--tw-prose-kbd-shadows": "var(--color-jet-900)",
            "--tw-prose-code": "var(--color-jet-900)",
            "--tw-prose-pre-code": "var(--color-jet-200)",
            "--tw-prose-pre-bg": "var(--color-jet-800)",
            "--tw-prose-th-borders": "var(--color-jet-300)",
            "--tw-prose-td-borders": "var(--color-jet-200)",
            "--tw-prose-invert-body": "var(--color-jet-300)",
            "--tw-prose-invert-headings": "var(--color-white)",
            "--tw-prose-invert-lead": "var(--color-jet-400)",
            "--tw-prose-invert-links": "var(--color-white)",
            "--tw-prose-invert-bold": "var(--color-white)",
            "--tw-prose-invert-counters": "var(--color-jet-400)",
            "--tw-prose-invert-bullets": "var(--color-jet-600)",
            "--tw-prose-invert-hr": "var(--color-jet-700)",
            "--tw-prose-invert-quotes": "var(--color-jet-100)",
            "--tw-prose-invert-quote-borders": "var(--color-jet-700)",
            "--tw-prose-invert-captions": "var(--color-jet-400)",
            "--tw-prose-invert-kbd": "var(--color-white)",
            "--tw-prose-invert-kbd-shadows": "var(--color-white)",
            "--tw-prose-invert-code": "var(--color-white)",
            "--tw-prose-invert-pre-code": "var(--color-jet-300)",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "var(--color-jet-600)",
            "--tw-prose-invert-td-borders": "var(--color-jet-700)",
          },
        },
      }),
    },
  },
}
