# REF - initial setup, proved to be missing content in latter half): https://blog.bitsrc.io/deploy-gatsby-to-firebase-hosting-with-github-actions-f24e3b807ea3
# REF - Better overall tutorial, outlines actual workflow file: https://blog.logrocket.com/setting-up-continuous-deployment-with-react-firebase-and-github-actions/

name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install packages
        run: yarn install

      - name: Run Tests
        env:
          CI: true
        run: yarn test:ci

      - name: Build
        run: yarn build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
          if-no-files-found: error


      # TODO: Build and upload Storybook artifact

  deploy:
    name: Deploy Site
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  # TODO: Deploy Storybook
