name: Continuous Integration

on: pull_request

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install packages
        run: npm install

      - name: Run Tests
        env:
          CI: true
        run: npm run test:ci
