name: Continuous Integration

on: pull_request

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install packages
        run: yarn install

      - name: Run Tests
        env:
          CI: true
        run: yarn test:ci
