name: Test and Lint CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test_and_lint:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn test:ci
